// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.API.Models.Db;

namespace Web.API.Migrations
{
    [DbContext(typeof(WebContext))]
    partial class WebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.API.Models.Db.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Username");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Web.API.Models.Db.Cliente", b =>
                {
                    b.OwnsOne("Web.API.Models.Db.Address", "Address", b1 =>
                        {
                            b1.Property<int?>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City");

                            b1.Property<string>("Street");

                            b1.Property<string>("Suite");

                            b1.Property<string>("Zipcode");

                            b1.ToTable("Cliente");

                            b1.HasOne("Web.API.Models.Db.Cliente")
                                .WithOne("Address")
                                .HasForeignKey("Web.API.Models.Db.Address", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("Web.API.Models.Db.Geo", "Geo", b2 =>
                                {
                                    b2.Property<int?>("AddressClienteId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Lat");

                                    b2.Property<string>("Lng");

                                    b2.ToTable("Cliente");

                                    b2.HasOne("Web.API.Models.Db.Address")
                                        .WithOne("Geo")
                                        .HasForeignKey("Web.API.Models.Db.Geo", "AddressClienteId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("Web.API.Models.Db.Company", "Company", b1 =>
                        {
                            b1.Property<int?>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bs");

                            b1.Property<string>("CatchPhrase");

                            b1.Property<string>("Name");

                            b1.ToTable("Cliente");

                            b1.HasOne("Web.API.Models.Db.Cliente")
                                .WithOne("Company")
                                .HasForeignKey("Web.API.Models.Db.Company", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
